add linter to mobile fisrt
Daniel-Kigozi/Mobile-First pull request #1
Opened 2022-09-21 17:24 UTC by Daniel-Kigozi

-Add linter to mobile-first
-add a mark up to mobile-first
-Add CSS for mobile-first

2022-09-21 20:28 UTC, Alfredbis29 requested changes
### Hi @Daniel-Kigozi ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters are passing. ✔

## Required Changes ♻️

- [ ] You've done a wonderful job so far, but there are some modifications you should do. I couldn't find your 'index.html' in your PR, so it appears you didn't make any changes to it when generating your PR, so I took these screenshots to show you what you need to modify in your 'Index.html' file. Please see the screenshots below. :point_down:  :point_down: 

**Index.html file please change this :arrow_down:** 

![num1](https://user-images.githubusercontent.com/88894525/191603072-f08134ed-d636-4b78-9a60-3dbad393118f.png)

**Index.html file please change this :arrow_down:** 

![num2](https://user-images.githubusercontent.com/88894525/191603175-d82e53a0-522d-4089-b429-fc2f2d90772f.png)

**Index.html file please change this :arrow_down:** 

![num3](https://user-images.githubusercontent.com/88894525/191603220-50b2f9a5-67f4-47a9-8b74-c19d576a5b90.png)



_Check the comments under the review._

## [Optional] suggestions:

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please remember to tag me @jerryowusu  in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-21 20:28 UTC, Alfredbis29 commented on styles.css
> +
- [ ] Good job thus far, but there are a few things you still need to focus on to make your project appear professional. Your design should appear the same as For Figma Design, as required for this project. Please make your design look like the Figma design. so that recruiters may recognize your efforts :wink:  :wink: 

- [ ] Your design and the one for Figma are pretty different.

Figma Design
![second](https://user-images.githubusercontent.com/88894525/191593640-1b29d5db-b90e-4778-8b3e-c3200f604053.png)

Your Design
![danielDesign](https://user-images.githubusercontent.com/88894525/191593702-1372b25d-b230-4090-bbbd-1a8f7981a8f6.png)

2022-09-22 08:32 UTC, Daniel-Kigozi commented
@Alfredbis29 I have made the changes in the index file and changed some CSS designs kindly review it for your approval

2022-09-22 12:24 UTC, GiuseppeTG approved these changes
Hi @Daniel-Kigozi  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥇 : 
Congratulations! 🎉 

![Alt Text](https://media3.giphy.com/media/nXxOjZrbnbRxS/giphy.gif)

## Highlights
✅ Professional documentation
✅ Clean code
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 12:29 UTC, GiuseppeTG commented
[OPTIONAL] I will mark this as optional because the previous reviewer did not ask for this specifically. To imitate the Figma design, you can inspect the elements on it and check the exact value for colors, font weight, line height, etc. as shown in the following image:

![Captura de Pantalla 2022-09-22 a la(s) 7 18 44 a  m](https://user-images.githubusercontent.com/86022690/191746542-46cfb757-9033-43f0-8d2e-3353a65bbaa1.png)

You are doing an excellent job, but these fixes will make it even better 🤓

2022-09-22 12:52 UTC, merged